import logging
from typing import Optional

from app.db.mongodb import get_db
from app.db.collections import VECTOR_STORE
from app.providers.base import VectorStoreProvider

logger = logging.getLogger("MongoDBVectorProvider")

class MongoDBVectorProvider(VectorStoreProvider):
    def __init__(self, index_name: str = "default_vector_index"):
        self.index_name = index_name
        logger.debug(f"Initialized MongoDBVectorProvider with index: {index_name}")

    async def add_documents(
        self,
        client_id: str,
        doc_id: str,
        chunks: list[str],
        embeddings: list[list[float]],
        metadatas: list[dict],
    ) -> None:
        try:
            db = get_db()
            logger.debug(f"Adding documents to MongoDB Vector Store for client_id: {client_id}, doc_id: {doc_id}")
            documents = []
            for i in range(len(chunks)):
                doc = {
                    "client_id": client_id,
                    "doc_id": doc_id,
                    "chunk_index": metadatas[i].get("chunk_index", i),
                    "text": chunks[i],
                    "embedding": embeddings[i],
                    "metadata": metadatas[i],
                }
                documents.append(doc)
            
            if documents:
                await db[VECTOR_STORE].insert_many(documents)
                logger.debug("Documents successfully added to MongoDB Vector Store.")
        except Exception as e:
            logger.error(f"Failed to add documents to MongoDB Vector Store: {e}")
            raise

    def _map_where_to_metadata(self, where: dict) -> dict:
        """Map the where clause fields (which are generated by metadata extraction)
        to the nested 'metadata' fields in MongoDB."""
        mapped = {}
        for k, v in where.items():
            if k == "$and":
                mapped["$and"] = [self._map_where_to_metadata(cond) for cond in v]
            elif k == "$or":
                mapped["$or"] = [self._map_where_to_metadata(cond) for cond in v]
            else:
                # MongoDB query operators start with $
                if k.startswith("$"):
                    mapped[k] = v
                else:
                    mapped[f"metadata.{k}"] = v
        return mapped

    async def search(
        self,
        client_id: str,
        query_embedding: list[float],
        top_k: int = 5,
        where: Optional[dict] = None,
    ) -> list[dict]:
        try:
            db = get_db()
            
            filter_query = {"client_id": client_id}
            if where:
                mapped_where = self._map_where_to_metadata(where)
                filter_query = {"$and": [{"client_id": client_id}, mapped_where]}
            
            pipeline = [
                {
                    "$vectorSearch": {
                        "index": self.index_name,
                        "path": "embedding",
                        "queryVector": query_embedding,
                        "numCandidates": top_k * 10,
                        "limit": top_k,
                        "filter": filter_query
                    }
                },
                {
                    "$project": {
                        "_id": 0,
                        "text": 1,
                        "metadata": 1,
                        "score": {"$meta": "vectorSearchScore"}
                    }
                }
            ]
            
            cursor = db[VECTOR_STORE].aggregate(pipeline)
            results = []
            async for doc in cursor:
                results.append({
                    "text": doc.get("text"),
                    "metadata": doc.get("metadata", {}),
                    "score": doc.get("score", 0.0),
                })
            
            # If a metadata filter was provided and we got too few results, try falling back
            if where and len(results) < 2:
                logger.debug("Metadata filter returned < 2 results, falling back to unfiltered search in MongoDB")
                fallback_pipeline = [
                    {
                        "$vectorSearch": {
                            "index": self.index_name,
                            "path": "embedding",
                            "queryVector": query_embedding,
                            "numCandidates": top_k * 10,
                            "limit": top_k,
                            "filter": {"client_id": client_id}
                        }
                    },
                    {
                        "$project": {
                            "_id": 0,
                            "text": 1,
                            "metadata": 1,
                            "score": {"$meta": "vectorSearchScore"}
                        }
                    }
                ]
                cursor = db[VECTOR_STORE].aggregate(fallback_pipeline)
                results = []
                async for doc in cursor:
                    results.append({
                        "text": doc.get("text"),
                        "metadata": doc.get("metadata", {}),
                        "score": doc.get("score", 0.0),
                    })

            return results
        except Exception as e:
            logger.error(f"MongoDB Vector Search operation failed: {e}")
            raise

    async def delete_document(self, client_id: str, doc_id: str) -> None:
        try:
            db = get_db()
            result = await db[VECTOR_STORE].delete_many({"client_id": client_id, "doc_id": doc_id})
            logger.debug(f"Deleted {result.deleted_count} chunks for document {doc_id}, client_id {client_id}")
        except Exception as e:
            logger.error(f"Failed to delete document {doc_id} from MongoDB Vector Store: {e}")
            raise
